name: drug-align-analysis
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - rdkit
  - pandas
  - pyarrow
  - biopython
  - scipy
  - pyyaml
  - pytorch
  - foldseek=10.941cd33
  - transformers=5.13.0
  - sentencepiece
  - safetensors
  - huggingface_hub
  - pip
  - pip:
      - fair-esm
      - unimol-tools==0.1.6
