#!/usr/bin/env python3
"""Run a small Uni-Mol molecular embedding smoke test on known EGFR ligands."""

from __future__ import annotations

import csv
import importlib.metadata
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import rdkit
import torch
from unimol_tools import UniMolRepr


ROOT = Path(__file__).resolve().parents[1]
INPUT_CSV = ROOT / "data" / "ligands" / "egfr_known_ligands.csv"
OUTPUT_DIR = ROOT / "outputs" / "molecule_embeddings" / "unimol_v1_84m"
OUTPUT_NPZ = OUTPUT_DIR / "egfr_named_ligands_smoke.npz"
OUTPUT_CSV = OUTPUT_DIR / "egfr_named_ligands_smoke.csv"
AUDIT_PATH = ROOT / "data" / "egfr-unimol-smoke-audit.json"

PREFERRED_NAMES = [
    "AFATINIB",
    "ERLOTINIB",
    "GEFITINIB",
    "OSIMERTINIB",
    "LAPATINIB",
    "NERATINIB",
    "MOBOCERTINIB",
    "BRIGATINIB",
]
SMOKE_SIZE = 8


def select_rows() -> list[dict[str, str]]:
    with INPUT_CSV.open(encoding="utf-8") as handle:
        rows = list(csv.DictReader(handle))

    selected = []
    seen_inchikeys = set()
    for preferred_name in PREFERRED_NAMES:
        for row in rows:
            if (
                row["molecule_pref_name"].upper() == preferred_name
                and row["inchikey"] not in seen_inchikeys
            ):
                selected.append(row)
                seen_inchikeys.add(row["inchikey"])
                break

    if len(selected) < SMOKE_SIZE:
        for row in rows:
            if row["inchikey"] not in seen_inchikeys:
                selected.append(row)
                seen_inchikeys.add(row["inchikey"])
            if len(selected) == SMOKE_SIZE:
                break
    if len(selected) != SMOKE_SIZE:
        raise RuntimeError(f"Expected {SMOKE_SIZE} smoke molecules, got {len(selected)}")
    return selected


def main() -> None:
    rows = select_rows()
    smiles = [row["canonical_smiles"] for row in rows]

    model = UniMolRepr(
        data_type="molecule",
        model_name="unimolv1",
        model_size="84m",
        remove_hs=False,
        batch_size=4,
        use_cuda=False,
    )
    result = model.get_repr(smiles, return_atomic_reprs=False)
    cls_values = result["cls_repr"] if isinstance(result, dict) else result
    cls_embeddings = np.asarray(cls_values, dtype=np.float32)
    if cls_embeddings.shape[0] != len(rows):
        raise RuntimeError(
            f"Embedding count mismatch: {cls_embeddings.shape[0]} != {len(rows)}"
        )
    if cls_embeddings.ndim != 2 or not np.isfinite(cls_embeddings).all():
        raise RuntimeError("Invalid Uni-Mol CLS embeddings")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        OUTPUT_NPZ,
        embeddings=cls_embeddings,
        molecule_chembl_ids=np.array([row["molecule_chembl_id"] for row in rows]),
        inchikeys=np.array([row["inchikey"] for row in rows]),
        smiles=np.array(smiles),
    )
    metadata_fields = [
        "molecule_chembl_id",
        "molecule_pref_name",
        "inchikey",
        "canonical_smiles",
        "assay_variant_mutation",
        "activity_type",
        "best_value_nm",
    ]
    with OUTPUT_CSV.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=metadata_fields)
        writer.writeheader()
        writer.writerows({field: row[field] for field in metadata_fields} for row in rows)

    audit = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "status": "pass",
        "package": "unimol-tools",
        "package_version": importlib.metadata.version("unimol-tools"),
        "model_name": "unimolv1",
        "model_size": "84m",
        "input_count": len(rows),
        "embedding_shape": list(cls_embeddings.shape),
        "device": "cpu",
        "remove_hs": False,
        "torch_version": torch.__version__,
        "rdkit_version": rdkit.__version__,
        "output": str(OUTPUT_NPZ.relative_to(ROOT)),
        "selected_molecules": [
            {
                "chembl_id": row["molecule_chembl_id"],
                "name": row["molecule_pref_name"],
                "inchikey": row["inchikey"],
            }
            for row in rows
        ],
        "limitations": [
            "Smoke test only; no downstream performance claim.",
            "Conformations are generated by the unimol-tools default pipeline.",
            "CPU inference was used because the official wrapper exposes CUDA/CPU, not MPS.",
        ],
    }
    AUDIT_PATH.write_text(
        json.dumps(audit, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(json.dumps(audit, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
